### ISSUE TITLE
Redundant size check

### ISSUE THREAD

**Issue by hrkrshnn** [frangio/cacheable-beacon-proxy#1]
https://github.com/frangio/cacheable-beacon-proxy/blob/78ccbbcca0f7157ddbceb81b3b65f7552758c308/contracts/CacheableBeaconProxy.sol#L34-L36

The check `if (cache.code.length > 0)` is redundant as it is done by the compiler in `CacheableBeaconImpl(cache).selfDestructIfCache(); `

**Comment by zach3040** [comment]
@hrkrshnn When I compile and run the test with version 0.8.13, it won't pass unless this size check is in there.

**Comment by frangio** [comment]
@zach3040 Yes, on second inspection PR #2 should not have been merged. The explicit check for code size was there to prevent a revert, which is necessary for functioning.

Thanks for raising this. My bad for not setting up the CI to run the tests. Reverted in c4710b42f4ca3e06ed8ab533a92892926e70d676.

**Comment by hrkrshnn** [comment]
Sorry about that 😬
